# Generated by Django 5.0.4 on 2024-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('audio', 'audio'), ('document', 'document')], default=1, max_length=255, verbose_name='file_type'),
            preserve_default=False,
        ),
    ]
